[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["/solmate/src=/lib/solmate/src"]

[fmt]
bracket_spacing = true
int_types = 'long'
line_length = 80
multiline_func_header = 'params_first'
number_underscore = 'thousands'
quote_style = 'double'
tab_width = 4
wrap_comments = true
